### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by TilenKelc** [TilenKelc/WebGl_Game#1]
Things todo:

#1 Development
- [x] Implement gltf loader into our game
- [x]  Camera rotation and movement
- [x] Implement shaders
- [x] Movement of gltf models and camera
- [x] Make a game map
- [x] Drone package droping
- [x] Adding gui interaction
- [x] Adding target places for box droping
- [x] Design and add Starting screen (buttons play, quit, highscore etc)

#2 Testing
- [ ] Test game for bugs

#3 Final product
- [ ] Make a video demonstration
- [ ] Make a report
- [ ] Submit
